### ISSUE TITLE
Issue: pgaudit Installation on Windows

### ISSUE THREAD

**Issue by japan-geek** [pgaudit/pgaudit#66] opened 2019-01-11 06:01 UTC
I have an issue related to "pgaudit". 
The issue is that the pgaudit does not log the "AUDIT" log.

I write the current situation and how I construct the environment.
If you find something wrong, please let me know.

[Current Situation]
I have PostgreSQL running on my Windows Server 2012 R2.
In order to install pgaudit, I downloaded the following files: 
	PostgreSQL install	: postgresql-10.1-2-windows-x64.exe
	PosgreSQL lib		: postgresql-10.1.tar.gz
	pgaudit compile	: pgaudit-1.2.0.zip

I tried to construct the environment with the files.
While constructing the environment, there are no error reported.
But pgaudit does not log the "AUDIT" log.
I have checked several websites but I could not figure out why "AUDIT" log is not logged.

[Environment Construction]

1 Install the PostgreSQL 
(1)	Execute "postgresql-10.1-2-windows-x64.exe" to install it.
(I was trying the introduce the pgaudit on the PostgreSQL which is installed with binary file.)

2 Creat the lib
(1) Expand "postgresql-10.1.tar.gz"
(2) Rename "config_default.pl" to "config.pl"
(Directory: "...\postgresql-10.1\src\tools\msvc")
(3) Start Win64 Command Prompt of Visual Studio
(4) Execute "cd ‘...\postgresql-10.1\src\tools\msvc’ "
(5) Execute "build"
(6) Confirm that "postgres.lib" has been built.
(Directory: "...\postgresql-10.1\Release\postgres\postgres.lib")

3 Compile the pgaudit
(1)	Unzip "pgaudit-1.2.0.zip"
(2)	Create Visual C++ - Win32 project "pgaudit" as DLL with Visual Studio 2015
(3)	Delete the source and header created automatically
(4)	Add "pgaudit.c" to the project
(5)	Add "pgaudit.def" to the project.
The contents of "pgaudit.def" are following:
	LIBRARY pgaudit
	EXPORTS
		pgaudit_ddl_command_end
		pgaudit_sql_drop
(6)	Choose "Release x64" for the building environment.
(7)	Add the following directory under the include directory:
	...\postgresql-10.1\src\include
	...\postgresql-10.1\src\include\port\win32_msvc
	...\postgresql-10.1\src\include\port\win32
(8)	Set "Enable C++ Exceptions" on the project
(9)	Add "...\postgresql-10.1\Release\postgres" to the library directory
(10)	 Add "postgres.lib" to the library
(11)	 Build them and confirm that "pgaudit.dll" has been built.

4 Construct the environment for the pgaudit
(1)	Copy the following files to "%POSTGRES_HOME%\share\extension": 
	...\pgaudit-1.2.0\pgaudit.control
	...\pgaudit-1.2.0\pgaudit—1.2.sql

(2)	Copy "pgaudit.dll" to the directory "% POSTGRES_HOME %\lib"
(3)	Write the following on "%PGDATA%\posgres.conf":
	shared_preload_libraries = 'pgaudit'		# (change requires restart)
	pgaudit.log = 'ALL'
	pgaudit.log_catalog = on
	pgaudit.log_level = log
	pgaudit.log_parameter = on
	pgaudit.log_relation = on
	pgaudit.log_statement_once = off
	pgaudit.role = 'auditor'
(4)	Restart the PostgreSQL service
(5)	Start "psql" with the command "psql -p port_num -U postgres"
(6)	Execute the following（The result are shown after the arrow）:
	create role audior ;		
		->CREATE ROLE
	show shared_preload_libraries ;	
		->pgaudit
	\du				
		->pgaudit  Cannt login  {}
		  postgres  Superuser…, 	{}
	show pgaudit.role ;		
		->auditor
	create extention pgaudit ;		
		->CREATE EXTENSION
	\dx				
		->adminpack 1.0 pg_catalog administrative functions for PostgreSQL
		  pgaudit  1.2 public	   provides auditing functionality
		  plpgsql  1.0 pg_catalog  PL/pgSQL procedural laguage
	select * from test_table ;
		->(The search results are shown)
(7)	Restart the PostgreSQL and execute the same command as (5)
(8)	Execute "select * from test_table ;"
(9)	Confirm the log:
(Directory: "%PGDATA%\log")
	LOG:  database system was shut down at 2019-01-10 17:15:44 JST
	LOG:  database system is ready to accept connections
	LOG:  statement: select * from test_table ;
（No "AUDIT" log has been logged.）

If you can not understand any of my English.
Please let me know. I will expalin it more.

**Comment by dwsteele** [comment] 2019-01-12 04:19
What does `show pgaudit.log` return?

**Comment by japan-geek** [comment] 2019-01-13 02:20
Thank you for your reply.
I have tried “show plaudits.log”.
It returns 'ALL'.

**Comment by dwsteele** [comment] 2019-01-24 16:52
You can try setting `pgaudit.log_client = on` and see if the audit messages come through in psql.  If not, then I'm not sure what else to check.  I'm not able to reproduce your environment.

**Comment by japan-geek** [comment] 2019-01-28 00:16
Thank you for your advice. But I could not get the AUDIT log.
I would like to make sure I have followed your advice correctly.
  1. Stop the PostgreSQL service
  2. Add pgaudit.log_client=on to “postgresql.conf”
  3. Restart the PostgreSQL service
  4. Start psql
  5. Execute the following command:
         show pgaudit.log ;             -> 'ALL'
         show pgaudit.log_client ;   ->'on'
         select * from test_table ;    ->The results are shown
  6. I have got the following logs:
        LOG: database system was shut down at 2019-01-25 13:45:26 JST
        LOG: database system is ready to accept connections
        LOG: statement: show pgaudit.log ;
        LOG: statement: show pgaudit.log_client ;
        LOG: statement: select * from test_table ;
        （No "AUDIT" log has been logged.）

Is there anything that I missed?

**Comment by dwsteele** [comment] 2019-01-31 08:39
This all looks right to me. so the problem may be with your build.  I don't have any Windows experience so I can't help with that.

**Comment by jconway** [comment] 2019-02-14 12:30
I have found that Postgres extensions on Windows are very sensitive to exactly how they are built. I would try to build the extension by dropping the pgaudit source code directory into a full Postgres source code tree under "contrib", and then build the entire thing following the docs for a Windows source build. Then take the resulting pgaudit.dll and use that.

Additionally, make sure that pgaudit.dll is in the correct place. Run:

  SELECT * FROM pg_config WHERE name = 'PKGLIBDIR';

and be sure pgaudit.dll is in that location.

**Comment by japan-geek** [comment] 2019-02-15 05:24
TO dwsteele
Thank you for your consideration and advice.

TO jconway
Thank you for your advice.
I will try to build pgaudit in the way you have taught me.

**Comment by jconway** [comment] 2019-02-15 15:55
Thanks. Please let us know how it goes.

**Comment by jconway** [comment] 2019-02-20 14:57
Independently I exchanged email with someone else that had apparently the same issue. He reported that after following my advice it solved his issue successfully. Hopefully it will do the same for you too.

**Comment by dwsteele** [comment] 2019-03-15 16:54
Hopefully that worked out for you.  Closing this now since it's been a while.

**Closed by dwsteele** 2019-03-15 16:54 UTC
Labels: question

**Comment by m1q2** [comment] 2019-07-26 05:43
@japan-geek , 
I am still trying to install pgaudit in my windows machine, but I am getting this error:
![image](https://user-images.githubusercontent.com/53328674/61928518-50f99580-af96-11e9-9a85-06ddcb6486d7.png)
