### ISSUE TITLE
Extension for 9.4

### ISSUE THREAD

**Issue by mbanck** [pgaudit/pgaudit#2] opened 2015-09-09 09:26 UTC
Currently pgaudit.c includes "tcop/deparse_utility.h" unconditionally, which is a 9.5 feature. Do you plan to support 9.4 as well, like the original code did? 

If not, would you accept patches to do so?

**Comment by dwsteele** [comment] 2015-09-09 13:10
We are planning to support <= 9.4 eventually but it has not been a priority.  We are primarily interested in the advanced audit logging capabilities that deparse and the new event trigger bring in 9.5.

I have 9.4 support in the branch where I was originally working on the submission to core.  The last commit that contains it is:
https://github.com/dwsteele/postgres/commit/e9a15401609617f0ab101695da0469e671e1d2b8

My plan for <= 9.4 support was to do it on a completely separate branch - this makes development a bit harder but would make things easier for end users.  Here are the reasons:

1) #DEFINES make compilation hard for less-experience users.
2) The regression test output is very different for 9.5 and <= 9.4
3) The pgaudit--1.0.sql file differs between 9.5 and <= 9.4 and I'm not sure it's good to put version checks in that file.
4) I think the drop event trigger brings very little to the table and for <= 9.4 I think it's best to remove it so there are no triggers to worry about.

If you are interested in developing a patch, I'd recommend starting from the develop branch, remove the event triggers, and pull the code from the commit referenced above back in.  Then run and check the regressions tests -- the output will definitely be a lot different, mostly missing object names in the DDL commands.  This is what I plan to do do eventually but it would certainly speed the process if you are willing to pitch in.

**Comment by dwsteele** [comment] 2015-09-15 14:43
I have found a potential showstopper to a 9.4 version.  The extension uses MemoryContextRegisterResetCallback() to allow more detailed information about events by maintaining an event stack and to clean up the event stack cases where an exception occurs and the normal callbacks are skipped.  This callback only exists in 9.5 and above.

Removing this callback would require a major refactor of the code as the event stack would no longer be maintainable.  I don't think there is an easy solution to this issue.

**Comment by dwsteele** [comment] 2016-03-13 14:26
I'm closing this because it is not likely this code will be ported to PG < 9.5.

**Closed by dwsteele** 2016-03-13 14:26 UTC
Labels: enhancement
